import swaggerJsdoc from "swagger-jsdoc";

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Clinical Management System API",
      description:
        "REST API for managing clinical appointments.\n\n" +
        "**Database:** MongoDB (Mongoose ODM)\n\n" +
        "**Collection:** `appointments`\n\n" +
        "All IDs are MongoDB ObjectId strings (24-character hex).\n\n" +
        "Timestamps (`created_at`, `updated_at`) are managed automatically.",
      version: "1.0.0",
    },
    servers: [
      {
        url: "http://localhost:3000",
        description: "Development server",
      },
    ],
    tags: [
      {
        name: "Health",
        description: "Server health check",
      },
      {
        name: "Appointments",
        description: "CRUD operations for the appointments collection",
      },
    ],
    paths: {
      "/health": {
        get: {
          summary: "Health check",
          tags: ["Health"],
          description: "Returns server status and current timestamp",
          responses: {
            200: {
              description: "Server is running",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: {
                      status: { type: "string", example: "ok" },
                      timestamp: {
                        type: "string",
                        format: "date-time",
                        example: "2026-03-11T10:00:00.000Z",
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    components: {
      schemas: {
        Appointment: {
          type: "object",
          description: "Appointment document stored in MongoDB",
          properties: {
            id: {
              type: "string",
              description: "MongoDB ObjectId",
              example: "507f1f77bcf86cd799439011",
            },
            patient_name: { type: "string", example: "Nikesh Sahoo" },
            doctor_name: { type: "string", example: "Dr. Sharma" },
            appointment_date: {
              type: "string",
              format: "date",
              description: "Date in YYYY-MM-DD format",
              example: "2026-03-15",
            },
            appointment_time: {
              type: "string",
              description: "Time in HH:MM 24-hour format",
              example: "10:30",
            },
            status: {
              type: "string",
              enum: ["scheduled", "completed", "cancelled", "no-show"],
              default: "scheduled",
              example: "scheduled",
            },
            reason: { type: "string", example: "General checkup" },
            created_at: {
              type: "string",
              format: "date-time",
              description: "Auto-generated by MongoDB",
            },
            updated_at: {
              type: "string",
              format: "date-time",
              description: "Auto-updated by MongoDB on each modification",
            },
          },
        },
        CreateAppointmentDTO: {
          type: "object",
          description: "Request body to create a new appointment",
          required: [
            "patient_name",
            "doctor_name",
            "appointment_date",
            "appointment_time",
            "reason",
          ],
          properties: {
            patient_name: { type: "string", example: "Nikesh Sahoo" },
            doctor_name: { type: "string", example: "Dr. Sharma" },
            appointment_date: {
              type: "string",
              format: "date",
              description: "Must be today or a future date (YYYY-MM-DD)",
              example: "2026-03-15",
            },
            appointment_time: {
              type: "string",
              description: "24-hour format HH:MM",
              example: "10:30",
            },
            status: {
              type: "string",
              enum: ["scheduled", "completed", "cancelled", "no-show"],
              description: "Optional. Defaults to 'scheduled'",
              example: "scheduled",
            },
            reason: { type: "string", example: "General checkup" },
          },
        },
        UpdateAppointmentDTO: {
          type: "object",
          description: "Request body to update an existing appointment. All fields are optional.",
          properties: {
            patient_name: { type: "string", example: "Nikesh Sahoo" },
            doctor_name: { type: "string", example: "Dr. Sharma" },
            appointment_date: {
              type: "string",
              format: "date",
              description: "Must be today or a future date (YYYY-MM-DD)",
              example: "2026-03-20",
            },
            appointment_time: {
              type: "string",
              description: "24-hour format HH:MM",
              example: "14:00",
            },
            status: {
              type: "string",
              enum: ["scheduled", "completed", "cancelled", "no-show"],
              example: "completed",
            },
            reason: { type: "string", example: "Consultation done" },
          },
        },
        ErrorResponse: {
          type: "object",
          properties: {
            error: { type: "string", example: "Appointment not found" },
          },
        },
        ValidationError: {
          type: "object",
          properties: {
            errors: {
              type: "array",
              items: { type: "string" },
              example: [
                "patient_name is required and must be a non-empty string",
                "appointment_date must be today or a future date",
              ],
            },
          },
        },
        PaginatedAppointments: {
          type: "object",
          description: "Paginated response for listing appointments",
          properties: {
            data: {
              type: "array",
              items: { $ref: "#/components/schemas/Appointment" },
            },
            total: { type: "integer", description: "Total matching records", example: 25 },
            page: { type: "integer", description: "Current page number", example: 1 },
            limit: { type: "integer", description: "Records per page", example: 10 },
            totalPages: { type: "integer", description: "Total number of pages", example: 3 },
          },
        },
      },
    },
  },
  apis: ["./src/routes/*.ts"],
};

const swaggerSpec = swaggerJsdoc(options);

export default swaggerSpec;
